[package]
name = "software_rendering"
version = "0.1.0"
authors = ["Thundzz <yacinenew@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
sdl2 = "0.32"
rand = "0.6.5"
time = "0.1.42"
nalgebra = "0.17.3"
nalgebra-glm = "0.3.0"